import { useState } from 'react'
import { Link } from 'react-router-dom'

import { BarChart, type BarDatum } from '@/components/charts/bar-chart'
import { ConfusionMatrixGrid } from '@/components/charts/confusion-matrix'
import { Badge, DecisionBadge } from '@/components/ui/badge'
import { Card, CardHeader, CardNote } from '@/components/ui/card'
import { Metric, ShareBar } from '@/components/ui/metric'
import { PageHeader } from '@/components/ui/page-header'
import { Pagination } from '@/components/ui/pagination'
import { QueryBoundary, TableSkeleton } from '@/components/ui/states'
import { DataTable, Td, Th, Tr } from '@/components/ui/table'
import { useQuery } from '@/hooks/use-query'
import { api, type FeedbackRecord } from '@/lib/api'
import { formatCount, formatDateTime, formatPercent, humanizeCode } from '@/lib/format'
import type { Tone } from '@/lib/risk'
import { cn } from '@/lib/utils'

const PAGE_SIZE = 20

const OUTCOMES = [
  'confirmed_fraud',
  'legitimate',
  'false_positive',
  'false_negative',
  'insufficient_evidence',
  'escalated',
] as const

/** Fraud findings read as danger, clean findings as positive, open ones neutral. */
function outcomeTone(outcome: string): Tone {
  switch (outcome) {
    case 'confirmed_fraud':
    case 'false_negative':
      return 'danger'
    case 'legitimate':
      return 'positive'
    case 'false_positive':
      return 'warning'
    default:
      return 'neutral'
  }
}

export function OutcomeBadge({ outcome }: { outcome: string }) {
  return (
    <Badge tone={outcomeTone(outcome)} glyph="◆">
      {outcome.replace(/_/g, ' ').toUpperCase()}
    </Badge>
  )
}

/**
 * Whether a label came from a person or from the demo seeder.
 *
 * The seeder records no `analyst_id` and marks each row in its notes; a real
 * analyst resolution carries neither marker. Distinguishing them on screen is
 * not decoration - presenting seeded labels as production ground truth would
 * make every metric on this page a claim the data does not support.
 */
function isSimulated(record: FeedbackRecord): boolean {
  return record.analyst_id === null && /simulat/i.test(record.notes ?? '')
}

function ProvenanceBadge({ record }: { record: FeedbackRecord }) {
  return isSimulated(record) ? (
    <Badge tone="warning" title="Generated by the demo seeder, not a person">
      SIMULATED
    </Badge>
  ) : (
    <Badge tone="brand" title="Recorded by an analyst resolving a review case">
      HUMAN
    </Badge>
  )
}

/**
 * The feedback dashboard.
 *
 * Two things this page is careful about, because both are easy to get wrong and
 * expensive when wrong:
 *
 * 1. It reports labelling *coverage* next to every count, so a reader cannot
 *    mistake 200 labels for a description of 20,000 transactions.
 * 2. The confusion matrix includes only ground-truth outcomes. Open outcomes are
 *    reported as excluded, and unlabelled transactions are absent entirely -
 *    they are not negative examples.
 */
export function FeedbackPage() {
  const [page, setPage] = useState(1)
  const [outcome, setOutcome] = useState('')

  const summary = useQuery((signal) => api.feedbackSummary(signal), [])
  const models = useQuery((signal) => api.modelMonitoring(signal), [])
  const list = useQuery(
    (signal) =>
      api.feedback({ page, page_size: PAGE_SIZE, outcome: outcome || undefined }, signal),
    [page, outcome],
  )

  const data = summary.data?.summary
  const coverage = models.data?.coverage

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        eyebrow="Casework"
        title="Analyst feedback"
        description="What analysts concluded, recorded beside the machine decision. Feedback never modifies a decision - the two are stored separately so disagreement stays measurable."
        meta={
          data ? (
            <span>
              <span className="numeric font-medium text-content-muted">
                {formatCount(data.total_feedback)}
              </span>{' '}
              labels covering{' '}
              <span className="numeric font-medium text-content-muted">
                {formatPercent(data.labelled_share_of_transactions, 2)}
              </span>{' '}
              of {formatCount(data.total_transactions)} transactions
            </span>
          ) : undefined
        }
      />

      {/* --- headline model quality ---------------------------------------- */}
      <Card>
        <CardHeader
          title="Model performance on labelled data"
          description="Computed only over transactions a person or the seeder actually labelled. Unlabelled is not the same as legitimate."
          actions={
            <Link to="/monitoring" className="text-sm font-medium text-brand hover:underline">
              Monitoring →
            </Link>
          }
        />
        <div className="mt-4">
          <QueryBoundary
            loading={models.loading}
            error={models.error}
            data={models.data}
            onRetry={models.refetch}
            loadingRows={3}
          >
            {(payload) =>
              payload.metrics.sufficient ? (
                <>
                  <dl className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">
                    {(
                      [
                        ['Precision', payload.metrics.precision, 'Of what it flagged, how much was fraud'],
                        ['Recall', payload.metrics.recall, 'Of the fraud present, how much it caught'],
                        ['F1', payload.metrics.f1, 'The harmonic mean of the two'],
                        [
                          'False positive rate',
                          payload.metrics.false_positive_rate,
                          'Legitimate traffic it flagged',
                        ],
                        [
                          'False negative rate',
                          payload.metrics.false_negative_rate,
                          'Fraud it let through',
                        ],
                      ] as const
                    ).map(([label, value, hint]) => (
                      <div
                        key={label}
                        className="rounded-lg border border-border-subtle bg-surface-sunken/40 p-3"
                      >
                        <dt className="text-[0.65rem] font-semibold tracking-[0.08em] text-content-muted uppercase">
                          {label}
                        </dt>
                        <dd className="numeric mt-0.5 text-2xl font-semibold">
                          {value === null ? '--' : value.toFixed(3)}
                        </dd>
                        <dd className="mt-1 text-xs leading-snug text-content-faint">{hint}</dd>
                      </div>
                    ))}
                  </dl>
                  {payload.metrics.selection_bias_note ? (
                    <CardNote>{payload.metrics.selection_bias_note}</CardNote>
                  ) : null}
                </>
              ) : (
                <div className="rounded-lg border border-dashed border-border-subtle bg-surface-sunken/40 px-4 py-5">
                  <p className="text-sm font-semibold text-content">
                    Not enough labels to report metrics
                  </p>
                  <p className="mt-1 text-sm text-content-muted">
                    {payload.metrics.message ??
                      `${formatCount(payload.metrics.labelled_samples)} of ${payload.metrics.minimum_required} required.`}{' '}
                    Reporting precision from a handful of labels would be a number without a
                    meaning.
                  </p>
                </div>
              )
            }
          </QueryBoundary>
        </div>
      </Card>

      {/* --- counts --------------------------------------------------------- */}
      <section aria-label="Feedback counts" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric
          label="Total labels"
          value={data ? formatCount(data.total_feedback) : '--'}
          scope={
            data
              ? `${formatPercent(data.labelled_share_of_transactions, 2)} of ${formatCount(data.total_transactions)} transactions`
              : 'Feedback records'
          }
          tone="brand"
          loading={summary.loading}
          emphasis
          visual={
            data ? <ShareBar share={data.labelled_share_of_transactions} tone="brand" /> : undefined
          }
        />
        <Metric
          label="Confirmed fraud"
          value={data ? formatCount(data.confirmed_fraud) : '--'}
          scope="Analyst verified fraud"
          tone="danger"
          loading={summary.loading}
          emphasis
        />
        <Metric
          label="False positives"
          value={data ? formatCount(data.false_positive) : '--'}
          scope="Flagged but legitimate"
          tone="warning"
          loading={summary.loading}
          emphasis
        />
        <Metric
          label="Ground-truth labels"
          value={data ? formatCount(data.ground_truth_labels) : '--'}
          scope="Usable for measuring the model"
          tone="positive"
          loading={summary.loading}
          emphasis
          detail={
            coverage
              ? `${formatCount(coverage.open_outcome_labels)} open outcomes excluded`
              : undefined
          }
        />
      </section>

      <section aria-label="Secondary counts" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric
          label="Legitimate"
          value={data ? formatCount(data.legitimate) : '--'}
          scope="Analyst verified legitimate"
          tone="positive"
          loading={summary.loading}
        />
        <Metric
          label="False negatives"
          value={data ? formatCount(data.false_negative) : '--'}
          scope="Approved but fraudulent"
          tone="danger"
          loading={summary.loading}
        />
        <Metric
          label="Escalated"
          value={data ? formatCount(data.escalated) : '--'}
          scope="Passed to a senior reviewer"
          tone="warning"
          loading={summary.loading}
        />
        <Metric
          label="Insufficient evidence"
          value={data ? formatCount(data.insufficient_evidence) : '--'}
          scope="Question left open, not a label"
          loading={summary.loading}
        />
      </section>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader
            title="Machine vs human"
            description="The engine's decision against what the analyst concluded was true."
          />
          <div className="mt-4">
            <QueryBoundary
              loading={summary.loading}
              error={summary.error}
              data={summary.data}
              onRetry={summary.refetch}
            >
              {(payload) => <ConfusionMatrixGrid matrix={payload.confusion_matrix} />}
            </QueryBoundary>
          </div>
          <CardNote>
            Only labelled transactions appear here. The{' '}
            <span className="numeric">
              {coverage ? formatCount(coverage.unlabelled) : 'remaining'}
            </span>{' '}
            unlabelled transactions are absent rather than counted as legitimate.
          </CardNote>
        </Card>

        <Card>
          <CardHeader
            title="Reason codes"
            description="A closed vocabulary, so the breakdown can be counted. Free-text notes are stored but never aggregated."
          />
          <div className="mt-4">
            <QueryBoundary
              loading={summary.loading}
              error={summary.error}
              data={summary.data}
              onRetry={summary.refetch}
              isEmpty={(payload) => payload.summary.by_reason.length === 0}
              emptyTitle="No feedback recorded yet"
              emptyDescription="Resolve a review case with structured feedback to populate this."
            >
              {(payload) => (
                <BarChart
                  data={payload.summary.by_reason.map<BarDatum>((bucket) => ({
                    label: humanizeCode(bucket.reason_code),
                    count: bucket.count,
                    tone: 'brand',
                  }))}
                />
              )}
            </QueryBoundary>
          </div>
        </Card>
      </div>

      <Card>
        <CardHeader
          title="Feedback records"
          description="Newest first. Each row keeps its machine decision, and says whether a person or the seeder produced the label."
          actions={
            <div className="flex flex-wrap gap-1.5" role="group" aria-label="Filter by outcome">
              {['', ...OUTCOMES].map((option) => (
                <button
                  key={option || 'all'}
                  type="button"
                  aria-pressed={outcome === option}
                  onClick={() => {
                    setOutcome(option)
                    setPage(1)
                  }}
                  className={cn(
                    'rounded-lg border px-2.5 py-1 text-xs font-medium transition-colors',
                    outcome === option
                      ? 'border-brand bg-brand text-brand-contrast'
                      : 'border-border-subtle text-content-muted hover:border-border-strong hover:text-content',
                  )}
                >
                  {option ? option.replace(/_/g, ' ') : 'All'}
                </button>
              ))}
            </div>
          }
        />

        <div className="mt-4">
          <QueryBoundary
            loading={list.loading}
            error={list.error}
            data={list.data}
            onRetry={list.refetch}
            isEmpty={(payload) => payload.items.length === 0}
            emptyTitle="No feedback matches this filter"
            emptyDescription="Resolve a review case and record an outcome to begin labelling."
            skeleton={<TableSkeleton rows={6} columns={7} />}
          >
            {(payload) => (
              <>
                <DataTable>
                  <thead>
                    <tr>
                      <Th>Transaction</Th>
                      <Th>Source</Th>
                      <Th>Machine decision</Th>
                      <Th>Feedback outcome</Th>
                      <Th>Reason</Th>
                      <Th>Notes</Th>
                      <Th>Recorded</Th>
                    </tr>
                  </thead>
                  <tbody>
                    {payload.items.map((item) => (
                      <Tr key={item.feedback_id}>
                        <Td>
                          <Link
                            to={`/transactions/${encodeURIComponent(item.transaction_id)}`}
                            className="numeric text-xs font-medium text-brand hover:underline"
                          >
                            {item.transaction_id}
                          </Link>
                        </Td>
                        <Td>
                          <ProvenanceBadge record={item} />
                        </Td>
                        <Td>
                          <DecisionBadge decision={item.machine_decision} />
                        </Td>
                        <Td>
                          <OutcomeBadge outcome={item.outcome} />
                        </Td>
                        <Td className="text-content-muted">{humanizeCode(item.reason_code)}</Td>
                        <Td
                          className="max-w-xs truncate text-content-faint"
                          title={item.notes ?? ''}
                        >
                          {item.notes ?? '--'}
                        </Td>
                        <Td className="numeric text-xs whitespace-nowrap text-content-muted">
                          {formatDateTime(item.created_at)}
                        </Td>
                      </Tr>
                    ))}
                  </tbody>
                </DataTable>
                <Pagination meta={payload.meta} onPageChange={setPage} itemLabel="records" />
              </>
            )}
          </QueryBoundary>
        </div>
        {coverage?.simulated_label_note ? <CardNote>{coverage.simulated_label_note}</CardNote> : null}
      </Card>
    </div>
  )
}
