"""Request and response models for the decision endpoint.

The response is designed to be *checkable*: every field either names a rule, a
reason code, a measured input or the policy version, so a reader can reconstruct
the decision from the payload alone. No field carries model prose.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from app.schemas.common import ORMModel
from app.schemas.risk import TRANSACTION_REFERENCE_PATTERN


class DecisionRequest(BaseModel):
    """Identifies the transaction to decide."""

    transaction_id: str = Field(
        min_length=1,
        max_length=64,
        pattern=TRANSACTION_REFERENCE_PATTERN,
        description="Transaction reference (e.g. TXN_SCENARIO_B_CURRENT) or numeric primary key",
        examples=["TXN_SCENARIO_B_CURRENT"],
    )


class RuleMatchRead(BaseModel):
    """One rule that fired, and the measured values that made it fire."""

    rule_id: str
    action: str
    reason_codes: list[str]
    conditions: list[str] = Field(
        description="Each condition carries the actual value it was evaluated against."
    )


class DecisionSignals(BaseModel):
    """The inputs the policy saw, copied into the response for auditability."""

    fraud_probability: float | None = None
    risk_score: int | None = None
    fraud_model_version: str | None = None
    anomaly_score: int | None = None
    anomaly_severity: str | None = None
    anomaly_model_version: str | None = None
    investigation_id: str | None = None
    investigation_confidence: float | None = None
    investigation_status: str | None = None


class DecisionResponse(ORMModel):
    """A policy decision and its full justification."""

    decision_id: str
    transaction_id: str
    decision: str = Field(description="APPROVE, STEP_UP, REVIEW or BLOCK.")
    policy_version: str
    matched_rules: list[str] = Field(description="Every rule that fired, in evaluation order.")
    deciding_rules: list[str] = Field(
        description="The subset of matched rules whose action became the outcome."
    )
    reason_codes: list[str]
    rule_matches: list[RuleMatchRead]
    explanation: str = Field(
        description=(
            "Assembled deterministically from the matched rules and their measured "
            "values. Not generated by a language model."
        )
    )
    requires_human_review: bool
    review_case_id: int | None = Field(
        default=None, description="The review case opened for this decision, when one was."
    )
    signals: DecisionSignals
    input_digest: str = Field(
        description=(
            "SHA-256 of the signals and the policy snapshot. Identical digests must "
            "produce identical decisions."
        )
    )
    decided_at: datetime


class DecisionHistoryResponse(BaseModel):
    """Every decision ever made about one transaction, oldest first."""

    transaction_id: str
    decisions: list[DecisionResponse]
