"""phase 6 risk decision engine

Adds the append-only ``risk_decisions`` table and links the review queue to it.

Written by hand rather than autogenerated: the running container serves a built
image, so ``--autogenerate`` compared the database against the *old* models and
produced an empty revision.

Two things this migration deliberately does not do:

* It adds no CHECK constraint for the widened ``AnalystDecisionType``. These
  enum columns are plain ``VARCHAR`` - SQLAlchemy's non-native ``Enum`` has
  defaulted to ``create_constraint=False`` since 1.4, and the deployed schema
  was verified to carry no such constraint - so the new ``escalated`` value
  needs no DDL. Validation happens in Python at bind time.
* It adds no unique constraint on ``risk_decisions.transaction_id``. Decisions
  are history: a transaction may be re-decided under a new policy version and
  every evaluation keeps its own row.

Revision ID: 5fe7ba2834e5
Revises: 06e114544f8a
Create Date: 2026-08-23 05:01:27.298900
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5fe7ba2834e5"
down_revision: str | None = "06e114544f8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSON_DOC = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    op.create_table(
        "risk_decisions",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "approve",
                "step_up",
                "review",
                "block",
                name="decisionaction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("matched_rules", JSON_DOC, nullable=False),
        sa.Column("reason_codes", JSON_DOC, nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("fraud_probability", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("fraud_model_version", sa.String(length=64), nullable=True),
        sa.Column("anomaly_score", sa.Integer(), nullable=True),
        sa.Column("anomaly_severity", sa.String(length=16), nullable=True),
        sa.Column("anomaly_model_version", sa.String(length=64), nullable=True),
        sa.Column("investigation_public_id", sa.String(length=32), nullable=True),
        sa.Column("investigation_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("detail", JSON_DOC, nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fraud_probability IS NULL OR (fraud_probability >= 0 AND fraud_probability <= 1)",
            name=op.f("ck_risk_decisions_decision_fraud_probability_range"),
        ),
        sa.CheckConstraint(
            "anomaly_score IS NULL OR (anomaly_score >= 0 AND anomaly_score <= 100)",
            name=op.f("ck_risk_decisions_decision_anomaly_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_risk_decisions_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    op.create_index(
        op.f("ix_risk_decisions_public_id"), "risk_decisions", ["public_id"], unique=True
    )
    op.create_index(
        op.f("ix_risk_decisions_transaction_id"), "risk_decisions", ["transaction_id"], unique=False
    )
    op.create_index(op.f("ix_risk_decisions_action"), "risk_decisions", ["action"], unique=False)
    op.create_index(
        op.f("ix_risk_decisions_policy_version"), "risk_decisions", ["policy_version"], unique=False
    )
    op.create_index(
        op.f("ix_risk_decisions_decided_at"), "risk_decisions", ["decided_at"], unique=False
    )
    op.create_index(
        op.f("ix_risk_decisions_requires_human_review"),
        "risk_decisions",
        ["requires_human_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_decisions_investigation_public_id"),
        "risk_decisions",
        ["investigation_public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_decisions_input_digest"), "risk_decisions", ["input_digest"], unique=False
    )
    op.create_index(
        "ix_risk_decisions_transaction_decided",
        "risk_decisions",
        ["transaction_id", "decided_at"],
        unique=False,
    )
    op.create_index(
        "ix_risk_decisions_policy_action",
        "risk_decisions",
        ["policy_version", "action"],
        unique=False,
    )

    op.add_column("review_cases", sa.Column("risk_decision_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "review_cases",
        sa.Column(
            "resolution",
            sa.Enum(
                "approved",
                "rejected",
                "escalated",
                name="reviewresolution",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.add_column("review_cases", sa.Column("resolution_reason", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_review_cases_risk_decision_id"),
        "review_cases",
        ["risk_decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_cases_resolution"), "review_cases", ["resolution"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_review_cases_risk_decision_id_risk_decisions"),
        "review_cases",
        "risk_decisions",
        ["risk_decision_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_review_cases_risk_decision_id_risk_decisions"),
        "review_cases",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_review_cases_resolution"), table_name="review_cases")
    op.drop_index(op.f("ix_review_cases_risk_decision_id"), table_name="review_cases")
    op.drop_column("review_cases", "resolution_reason")
    op.drop_column("review_cases", "resolution")
    op.drop_column("review_cases", "risk_decision_id")

    op.drop_index("ix_risk_decisions_policy_action", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_transaction_decided", table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_input_digest"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_investigation_public_id"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_requires_human_review"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_decided_at"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_policy_version"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_action"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_transaction_id"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_public_id"), table_name="risk_decisions")
    op.drop_table("risk_decisions")
