"""phase 2 payment data universe

Revision ID: 199bd894a72e
Revises: 
Create Date: 2026-08-22 14:54:40.944258
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '199bd894a72e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.Enum('android', 'ios', 'web_desktop', 'web_mobile', name='devicetype', native_enum=False, length=32), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_first_seen_at'), 'devices', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_is_trusted'), 'devices', ['is_trusted'], unique=False)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reputation_score >= 0 AND reputation_score <= 100', name=op.f('ck_ip_addresses_reputation_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_addresses'))
    )
    op.create_index(op.f('ix_ip_addresses_country'), 'ip_addresses', ['country'], unique=False)
    op.create_index(op.f('ix_ip_addresses_first_seen_at'), 'ip_addresses', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_ip_addresses_ip_address'), 'ip_addresses', ['ip_address'], unique=True)
    op.create_index(op.f('ix_ip_addresses_last_seen_at'), 'ip_addresses', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_ip_addresses_reputation_score'), 'ip_addresses', ['reputation_score'], unique=False)
    op.create_table('merchants',
    sa.Column('external_merchant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=True)
    op.create_index(op.f('ix_merchants_external_merchant_id'), 'merchants', ['external_merchant_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('merchant', 'risk_analyst', 'admin', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('customers',
    sa.Column('merchant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_customer_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('account_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('average_transaction_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('successful_transaction_count', sa.Integer(), nullable=False),
    sa.Column('failed_transaction_count', sa.Integer(), nullable=False),
    sa.Column('chargeback_count', sa.Integer(), nullable=False),
    sa.Column('historical_risk_level', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_customers_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('merchant_id', 'external_customer_id', name='uq_customers_merchant_external_id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index('ix_customers_merchant_risk', 'customers', ['merchant_id', 'historical_risk_level'], unique=False)
    op.create_table('risk_rules',
    sa.Column('merchant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action', sa.Enum('allow', 'flag', 'review', 'step_up', 'block', name='ruleaction', native_enum=False, length=32), nullable=False),
    sa.Column('risk_adjustment', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_adjustment >= -100 AND risk_adjustment <= 100', name=op.f('ck_risk_rules_risk_adjustment_range')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_risk_rules_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_index(op.f('ix_risk_rules_is_active'), 'risk_rules', ['is_active'], unique=False)
    op.create_index('ix_risk_rules_merchant_active', 'risk_rules', ['merchant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_risk_rules_merchant_id'), 'risk_rules', ['merchant_id'], unique=False)
    op.create_table('customer_devices',
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('first_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_devices_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_customer_devices_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'device_id', name=op.f('pk_customer_devices'))
    )
    op.create_index('ix_customer_devices_device_customer', 'customer_devices', ['device_id', 'customer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ip_address_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('card', 'upi', 'netbanking', 'wallet', 'emi', name='paymentmethod', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('successful', 'failed', 'pending', 'reversed', name='transactionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.CheckConstraint('failed_attempts >= 0', name=op.f('ck_transactions_failed_attempts_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_transactions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_transactions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], name=op.f('fk_transactions_ip_address_id_ip_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_transactions_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_country'), 'transactions', ['country'], unique=False)
    op.create_index('ix_transactions_customer_time', 'transactions', ['customer_id', 'transaction_timestamp'], unique=False)
    op.create_index('ix_transactions_device_time', 'transactions', ['device_id', 'transaction_timestamp'], unique=False)
    op.create_index('ix_transactions_fraud_time', 'transactions', ['is_fraud', 'transaction_timestamp'], unique=False)
    op.create_index('ix_transactions_ip_time', 'transactions', ['ip_address_id', 'transaction_timestamp'], unique=False)
    op.create_index('ix_transactions_merchant_time', 'transactions', ['merchant_id', 'transaction_timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_payment_method'), 'transactions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_timestamp'), 'transactions', ['transaction_timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_type', sa.Enum('system', 'agent', 'analyst', 'merchant', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=96), nullable=True),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('event_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_audit_logs_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index('ix_audit_logs_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_transaction_created', 'audit_logs', ['transaction_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    op.create_table('investigations',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='investigationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommended_action', sa.Enum('allow', 'review', 'step_up', 'block', name='recommendedaction', native_enum=False, length=32), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_investigations_confidence_range')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_investigations_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_transaction_id'), 'investigations', ['transaction_id'], unique=True)
    op.create_table('review_cases',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'escalated', name='reviewcasestatus', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_review_cases_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_review_cases_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_cases'))
    )
    op.create_index(op.f('ix_review_cases_assigned_to'), 'review_cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_index('ix_review_cases_status_created', 'review_cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_cases_transaction_id'), 'review_cases', ['transaction_id'], unique=True)
    op.create_table('risk_predictions',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fraud_probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fraud_probability >= 0 AND fraud_probability <= 1', name=op.f('ck_risk_predictions_fraud_probability_range')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name=op.f('ck_risk_predictions_risk_score_range')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_risk_predictions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_predictions'))
    )
    op.create_index(op.f('ix_risk_predictions_model_version'), 'risk_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_risk_predictions_risk_score'), 'risk_predictions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_predictions_transaction_id'), 'risk_predictions', ['transaction_id'], unique=True)
    op.create_table('risk_signals',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('signal_name', sa.String(length=96), nullable=False),
    sa.Column('signal_value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='signalseverity', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_risk_signals_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_signals'))
    )
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_signal_name'), 'risk_signals', ['signal_name'], unique=False)
    op.create_index(op.f('ix_risk_signals_source'), 'risk_signals', ['source'], unique=False)
    op.create_index(op.f('ix_risk_signals_transaction_id'), 'risk_signals', ['transaction_id'], unique=False)
    op.create_index('ix_risk_signals_transaction_name', 'risk_signals', ['transaction_id', 'signal_name'], unique=False)
    op.create_table('analyst_decisions',
    sa.Column('review_case_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('analyst_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision', sa.Enum('approve', 'block', 'step_up', 'false_positive', 'confirmed_fraud', name='analystdecisiontype', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], name=op.f('fk_analyst_decisions_analyst_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_case_id'], ['review_cases.id'], name=op.f('fk_analyst_decisions_review_case_id_review_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyst_decisions'))
    )
    op.create_index(op.f('ix_analyst_decisions_analyst_id'), 'analyst_decisions', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_analyst_decisions_decision'), 'analyst_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_analyst_decisions_review_case_id'), 'analyst_decisions', ['review_case_id'], unique=False)
    op.create_table('model_feedback',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actual_outcome', sa.Enum('legitimate', 'fraud', 'unknown', name='actualoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('analyst_decision', sa.Enum('approve', 'block', 'step_up', 'false_positive', 'confirmed_fraud', name='analystdecisiontype', native_enum=False, length=32), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.id'], name=op.f('fk_model_feedback_prediction_id_risk_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_model_feedback_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_feedback'))
    )
    op.create_index(op.f('ix_model_feedback_actual_outcome'), 'model_feedback', ['actual_outcome'], unique=False)
    op.create_index(op.f('ix_model_feedback_prediction_id'), 'model_feedback', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_model_feedback_transaction_id'), 'model_feedback', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_feedback_transaction_id'), table_name='model_feedback')
    op.drop_index(op.f('ix_model_feedback_prediction_id'), table_name='model_feedback')
    op.drop_index(op.f('ix_model_feedback_actual_outcome'), table_name='model_feedback')
    op.drop_table('model_feedback')
    op.drop_index(op.f('ix_analyst_decisions_review_case_id'), table_name='analyst_decisions')
    op.drop_index(op.f('ix_analyst_decisions_decision'), table_name='analyst_decisions')
    op.drop_index(op.f('ix_analyst_decisions_analyst_id'), table_name='analyst_decisions')
    op.drop_table('analyst_decisions')
    op.drop_index('ix_risk_signals_transaction_name', table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_transaction_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_source'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_signal_name'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_risk_predictions_transaction_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_risk_score'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_model_version'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_review_cases_transaction_id'), table_name='review_cases')
    op.drop_index('ix_review_cases_status_created', table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_assigned_to'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_investigations_transaction_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_transaction_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_transactions_transaction_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_method'), table_name='transactions')
    op.drop_index('ix_transactions_merchant_time', table_name='transactions')
    op.drop_index('ix_transactions_ip_time', table_name='transactions')
    op.drop_index('ix_transactions_fraud_time', table_name='transactions')
    op.drop_index('ix_transactions_device_time', table_name='transactions')
    op.drop_index('ix_transactions_customer_time', table_name='transactions')
    op.drop_index(op.f('ix_transactions_country'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_customer_devices_device_customer', table_name='customer_devices')
    op.drop_table('customer_devices')
    op.drop_index(op.f('ix_risk_rules_merchant_id'), table_name='risk_rules')
    op.drop_index('ix_risk_rules_merchant_active', table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_is_active'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index('ix_customers_merchant_risk', table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_merchants_external_merchant_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_ip_addresses_reputation_score'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_last_seen_at'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_ip_address'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_first_seen_at'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_country'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_trusted'), table_name='devices')
    op.drop_index(op.f('ix_devices_first_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
