"""phase 5 investigation agent records

Revision ID: 06e114544f8a
Revises: 199bd894a72e
Create Date: 2026-08-22 23:07:11.504484
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06e114544f8a'
down_revision: str | None = '199bd894a72e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('public_id', sa.String(length=32), nullable=True))
    op.add_column('investigations', sa.Column('iteration_count', sa.Integer(), nullable=False))
    op.add_column('investigations', sa.Column('agent_is_mock', sa.Boolean(), nullable=False))
    op.add_column('investigations', sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_investigations_agent_is_mock'), 'investigations', ['agent_is_mock'], unique=False)
    op.create_index(op.f('ix_investigations_public_id'), 'investigations', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_public_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_agent_is_mock'), table_name='investigations')
    op.drop_column('investigations', 'report')
    op.drop_column('investigations', 'agent_is_mock')
    op.drop_column('investigations', 'iteration_count')
    op.drop_column('investigations', 'public_id')
    # ### end Alembic commands ###
